export default [
    { id: 1, name: "Buenos Aires", createdAt: new Date(), updatedAt: new Date() },
    { id: 2, name: "Catamarca", createdAt: new Date(), updatedAt: new Date() },
    { id: 3, name: "Chaco", createdAt: new Date(), updatedAt: new Date() },
    { id: 4, name: "Chubut", createdAt: new Date(), updatedAt: new Date() },
    { id: 5, name: "Córdoba", createdAt: new Date(), updatedAt: new Date() },
    { id: 6, name: "Corrientes", createdAt: new Date(), updatedAt: new Date() },
    { id: 7, name: "Entre Ríos", createdAt: new Date(), updatedAt: new Date() },
    { id: 8, name: "Formosa", createdAt: new Date(), updatedAt: new Date() },
    { id: 9, name: "Jujuy", createdAt: new Date(), updatedAt: new Date() },
    { id: 10, name: "La Pampa", createdAt: new Date(), updatedAt: new Date() },
    { id: 11, name: "La Rioja", createdAt: new Date(), updatedAt: new Date() },
    { id: 12, name: "Mendoza", createdAt: new Date(), updatedAt: new Date() },
    { id: 13, name: "Misiones", createdAt: new Date(), updatedAt: new Date() },
    { id: 14, name: "Neuquén", createdAt: new Date(), updatedAt: new Date() },
    { id: 15, name: "Río Negro", createdAt: new Date(), updatedAt: new Date() },
    { id: 16, name: "Salta", createdAt: new Date(), updatedAt: new Date() },
    { id: 17, name: "San Juan", createdAt: new Date(), updatedAt: new Date() },
    { id: 18, name: "San Luis", createdAt: new Date(), updatedAt: new Date() },
    { id: 19, name: "Santa Cruz", createdAt: new Date(), updatedAt: new Date() },
    { id: 20, name: "Santa Fe", createdAt: new Date(), updatedAt: new Date() },
    { id: 21, name: "Santiago del Estero", createdAt: new Date(), updatedAt: new Date() },
    { id: 22, name: "Tierra del Fuego", createdAt: new Date(), updatedAt: new Date() },
    { id: 23, name: "Tucumán", createdAt: new Date(), updatedAt: new Date() },
    { id: 24, name: "CABA", createdAt: new Date(), updatedAt: new Date() },
    { id: 25, name: "Nacional", createdAt: new Date(), updatedAt: new Date() }
]