export default [
    { id: 1, permission: 'create-patient', createdAt: new Date(), updatedAt: new Date() },
    { id: 2, permission: 'create-professional', createdAt: new Date(), updatedAt: new Date() },
    { id: 3, permission: 'create-insurance', createdAt: new Date(), updatedAt: new Date() },
    { id: 4, permission: 'create-institution', createdAt: new Date(), updatedAt: new Date() },
    { id: 5, permission: 'create-role', createdAt: new Date(), updatedAt: new Date() },
    { id: 6, permission: 'create-permission', createdAt: new Date(), updatedAt: new Date() },
    { id: 7, permission: 'create-speciality', createdAt: new Date(), updatedAt: new Date() },

    { id: 8, permission: 'get-patients', createdAt: new Date(), updatedAt: new Date() },
    { id: 9, permission: 'get-professionals', createdAt: new Date(), updatedAt: new Date() },
    { id: 10, permission: 'get-insurances', createdAt: new Date(), updatedAt: new Date() },
    { id: 11, permission: 'get-institutions', createdAt: new Date(), updatedAt: new Date() },
    { id: 12, permission: 'get-roles', createdAt: new Date(), updatedAt: new Date() },
    { id: 13, permission: 'get-permissions', createdAt: new Date(), updatedAt: new Date() },
    { id: 14, permission: 'get-specialities', createdAt: new Date(), updatedAt: new Date() },
    { id: 15, permission: 'get-users', createdAt: new Date(), updatedAt: new Date() },

    { id: 16, permission: 'get-patient', createdAt: new Date(), updatedAt: new Date() },
    { id: 17, permission: 'get-professional', createdAt: new Date(), updatedAt: new Date() },
    { id: 18, permission: 'get-insurance', createdAt: new Date(), updatedAt: new Date() },
    { id: 19, permission: 'get-institution', createdAt: new Date(), updatedAt: new Date() },
    { id: 20, permission: 'get-role', createdAt: new Date(), updatedAt: new Date() },
    { id: 21, permission: 'get-permission', createdAt: new Date(), updatedAt: new Date() },
    { id: 22, permission: 'get-speciality', createdAt: new Date(), updatedAt: new Date() },
    { id: 23, permission: 'get-user', createdAt: new Date(), updatedAt: new Date() },

    { id: 24, permission: 'update-patient', createdAt: new Date(), updatedAt: new Date() },
    { id: 25, permission: 'update-professional', createdAt: new Date(), updatedAt: new Date() },
    { id: 26, permission: 'update-insurance', createdAt: new Date(), updatedAt: new Date() },
    { id: 27, permission: 'update-institution', createdAt: new Date(), updatedAt: new Date() },
    { id: 28, permission: 'update-role', createdAt: new Date(), updatedAt: new Date() },
    { id: 29, permission: 'update-permission', createdAt: new Date(), updatedAt: new Date() },
    { id: 30, permission: 'update-speciality', createdAt: new Date(), updatedAt: new Date() },
    { id: 31, permission: 'update-user', createdAt: new Date(), updatedAt: new Date() },

    { id: 32, permission: 'delete-patient', createdAt: new Date(), updatedAt: new Date() },
    { id: 33, permission: 'delete-professional', createdAt: new Date(), updatedAt: new Date() },
    { id: 34, permission: 'delete-insurance', createdAt: new Date(), updatedAt: new Date() },
    { id: 35, permission: 'delete-institution', createdAt: new Date(), updatedAt: new Date() },
    { id: 36, permission: 'delete-role', createdAt: new Date(), updatedAt: new Date() },
    { id: 37, permission: 'delete-permission', createdAt: new Date(), updatedAt: new Date() },
    { id: 38, permission: 'delete-speciality', createdAt: new Date(), updatedAt: new Date() },
    { id: 39, permission: 'delete-user', createdAt: new Date(), updatedAt: new Date() },

    { id: 40, permission: 'get-pathologies', createdAt: new Date(), updatedAt: new Date() },
    { id: 41, permission: 'get-pathology', createdAt: new Date(), updatedAt: new Date() },

    { id: 42, permission: 'create-pathology', createdAt: new Date(), updatedAt: new Date() },
    { id: 43, permission: 'update-pathology', createdAt: new Date(), updatedAt: new Date() },
    { id: 44, permission: 'delete-pathology', createdAt: new Date(), updatedAt: new Date() },
]