import { ADMIN_PASS, ADMIN_USERNAME } from "../../config/env.config.js";
import { createHash } from "../../utils/bcrypt.util.js";

export default [
    { 
        id: 1,
        role_id: 1,
        email: 'admin@default.com',
        password: createHash(ADMIN_PASS),
        username: ADMIN_USERNAME,
        first_name: 'admin',
        last_name: 'admin',
        phone: null,
        dni: null,
        image: null,
        locality: null,
        province: null,
        address: null,
        updated_pass: true,
        createdAt: new Date(), 
        updatedAt: new Date() 
    },
    { 
        id: 2,
        role_id: 2,
        email: 'patient@default.com',
        password: createHash('Patient1!'),
        username: 'patient',
        first_name: 'patient',
        last_name: 'patient',
        phone: null,
        dni: null,
        image: null,
        locality: null,
        province: null,
        address: null,
        updated_pass: true,
        createdAt: new Date(), 
        updatedAt: new Date() 
    },
    { 
        id: 3,
        role_id: 3,
        email: 'professional@default.com',
        password: createHash('Professional1!'),
        username: 'professional',
        first_name: 'professional',
        last_name: 'professional',
        phone: null,
        dni: null,
        image: null,
        locality: null,
        province: null,
        address: null,
        updated_pass: true,
        createdAt: new Date(), 
        updatedAt: new Date() 
    },
    { 
        id: 4,
        role_id: 4,
        email: 'insurance@default.com',
        password: createHash('Insurance1!'),
        username: 'insurance',
        first_name: 'insurance',
        last_name: 'insurance',
        phone: null,
        dni: null,
        image: null,
        locality: null,
        province: null,
        address: null,
        updated_pass: true,
        createdAt: new Date(), 
        updatedAt: new Date() 
    },
    { 
        id: 5,
        role_id: 5,
        email: 'institution@default.com',
        password: createHash('Institution1!'),
        username: 'institution',
        first_name: 'institution',
        last_name: 'institution',
        phone: null,
        dni: null,
        image: null,
        locality: null,
        province: null,
        address: null,
        updated_pass: true,
        createdAt: new Date(), 
        updatedAt: new Date() 
    }
]